version: '3.8'

services:
  oracle-db:
    image: oracleinanutshell/oracle-xe-11g
    ports:
      - "1521:1521"
      - "8080:8080"
    environment:
      ORACLE_ALLOW_REMOTE: 'true'
      ORACLE_DISABLE_ASYNCH_IO: 'true'
    volumes:
      - oracle-data:/u01/app/oracle

  sqlplus:
    image: oracleinanutshell/oracle-xe-11g
    entrypoint: ["/bin/bash", "-c", "tail -f /dev/null"]

volumes:
  oracle-data:
